%YAML 1.2
---
Application:
    debug: True
    cookie_secret: this_isnt_very_secret_replace_me 
    site_name: Tornado Project Stub
    static_path: __base_path__/static/
    ui_modules: project.modules
    xsrf_cookies: True

HTTPServer:
    no_keep_alive: False
    ports: [8080,8081]

Logging:
    directory: logs
    filename: log.txt
    format: "%(levelname) -10s %(asctime)s %(message)s"
    # Valid values: debug, info, warning, error, critical
    level: debug
#    handler: syslog
#    syslog:
#        address: localhost
#        facility: local6

RequestHandlers:
<<<<<<< HEAD
    /: project.apps.Home
=======
    0: [/, project.apps.Home]
>>>>>>> a328e447a376855d68e5192cdb1f5cc61ca3da83
